### PR TITLE
fix(config): remove adult session related items from the public confi…

### PR DESCRIPTION
**Pull request by ProbablePrime**
…g file

### CODE REVIEW

**Comment by GrayBoltWolf** [comment]
Users are free to [download any config they wish](https://github.com/Resonite-Community-Projects/resonite-pterodactyl/blob/b35a4f1f73a1f9077b58a4983474ec8181f90c2d/installScript.sh#L21), this is provided as a template for some of the larger communities in Resonite for a 1-click install. As Resonite does not have any access mechanisms for simple adult world browsing, and the major communities also host adult sessions, this will not be removed as it then breaks compatibility with the [Adult Session Browser](https://github.com/Resonite-Community-Projects/adult-session-browser).

**Comment by ProbablePrime** [comment]
This is somewhat problematic, a general use application should not contain configuration required for its production use by the owner. Generally you'd store a generic config on the GitHub and use a private repository or alternate location with configuration required for the owner's production use.

As it stands, leaving that URL in there by default opens users up to potential implications(Security,Privacy etc) that might be unclear due to its presence because by default it is included.

**Comment by GrayBoltWolf** [comment]
I do not use this egg myself, our community partners (Oasis, USFN, etc) use this egg for some events, and thus the config remains public so individual headless servers can download it. I'm happy to add a disclaimer to the readme detailing a recommendation against general use, it was unexpected at creation time that anyone other than highly technical users would be implementing this architecture.

The other projects in this github org are all geared towards large scale communities, not individual users.

**Comment by ProbablePrime** [comment]
I understand, but even at a large scale, I generally wouldn't recommend leaving those there. There could be a large scale production use case for this one day that is for science, education etc. and for some just seeing that there might be enough to convince them to not use it.

It is however up to you and your community though.

**Pull request closed without merging**
